### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by Martenius1** [KrnkTV/qb-nitro#2]
Hey, I get this error installing sql file, yes I tried somethings, but they didn't work and kind of tried understanding the problem, but everything I did it didn't work.
![image](https://user-images.githubusercontent.com/101430409/167904505-bd6ecb0c-4c66-4e0a-a7ea-5f74e149b07c.png)

**Comment by Howsn** [comment]
I have the same problem :(

**Comment by SebastianMajcher2005** [comment]
Maybe u write some letters wrong in your code.Chceck because the error is "something wrong with syntax"

**Comment by Martenius1** [comment]
Well I downloaded straight from the github and didn't change anything so when it didn't work, then I changed somethings, but still nothing happend.
